### ISSUE TITLE
Pinecone issue

### ISSUE THREAD

**Issue by DialogIntelligens** [jirispilka/fastapi-pydantic-v2-benchmark#1]
Hello,
The pinecone on apify is not working anymore, I kind of rely on it for our company :).

So if you could take a look at it when you have time.

See my issue made in Apify.
:)

**Comment by jirispilka** [comment]
Hi, thank you for bringing this to my attention! I apologize for missing the issue with the Pinecone integration. I'm very sorry for any inconvenience caused

**Comment by DialogIntelligens** [comment]
All good, looking forward to seeing it fixed :)
